// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2011a.126 Production Release
//  HLS Date:       Wed Aug  8 00:52:07 PDT 2012
// 
//  Generated by:   ml7715@EEWS104A-020
//  Generated date: Tue Mar 15 15:54:34 2016
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    mean_vga_core
// ------------------------------------------------------------------


module mean_vga_core (
  clk, en, arst_n, vin_rsc_mgc_in_wire_d, vout_rsc_mgc_out_stdreg_d
);
  input clk;
  input en;
  input arst_n;
  input [149:0] vin_rsc_mgc_in_wire_d;
  output [29:0] vout_rsc_mgc_out_stdreg_d;
  reg [29:0] vout_rsc_mgc_out_stdreg_d;


  // Interconnect Declarations
  reg [149:0] regs_regs_3_sva_1;
  reg [149:0] regs_regs_2_sva_1;
  reg [15:0] red_sva_1;
  wire [16:0] nl_red_sva_1;
  reg [15:0] green_sva_1;
  wire [16:0] nl_green_sva_1;
  reg [15:0] blue_sva_1;
  wire [16:0] nl_blue_sva_1;
  reg [9:0] regs_regs_slc_regs_regs_4_itm;
  reg [9:0] regs_regs_slc_regs_regs_4_6_itm;
  reg [9:0] regs_regs_slc_regs_regs_4_1_itm;
  reg [9:0] regs_regs_slc_regs_regs_4_10_itm;
  reg [9:0] regs_regs_slc_regs_regs_4_7_itm;
  reg [9:0] regs_regs_slc_regs_regs_4_13_itm;
  reg [9:0] regs_regs_slc_regs_regs_4_4_itm;
  reg [9:0] regs_regs_slc_regs_regs_4_2_itm;
  reg [9:0] regs_regs_slc_regs_regs_4_11_itm;
  reg [9:0] regs_regs_slc_regs_regs_4_8_itm;
  reg [9:0] regs_regs_slc_regs_regs_4_14_itm;
  reg [9:0] regs_regs_slc_regs_regs_4_5_itm;
  reg [9:0] regs_regs_slc_regs_regs_4_3_itm;
  reg [9:0] regs_regs_slc_regs_regs_4_21_itm;
  reg [9:0] regs_regs_slc_regs_regs_4_22_itm;
  reg main_stage_0_2;
  reg [149:0] reg_regs_regs_0_sva_cse;
  wire [16:0] FRAME_acc_228_psp_sva;
  wire [17:0] nl_FRAME_acc_228_psp_sva;
  wire [5:0] FRAME_acc_230_psp_sva;
  wire [7:0] nl_FRAME_acc_230_psp_sva;
  wire [6:0] FRAME_acc_229_psp_sva;
  wire [8:0] nl_FRAME_acc_229_psp_sva;
  wire [16:0] FRAME_acc_231_psp_sva;
  wire [17:0] nl_FRAME_acc_231_psp_sva;
  wire [6:0] FRAME_acc_232_psp_sva;
  wire [8:0] nl_FRAME_acc_232_psp_sva;
  wire [5:0] FRAME_acc_233_psp_sva;
  wire [7:0] nl_FRAME_acc_233_psp_sva;
  wire [16:0] FRAME_acc_234_psp_sva;
  wire [17:0] nl_FRAME_acc_234_psp_sva;
  wire [6:0] FRAME_acc_235_psp_sva;
  wire [8:0] nl_FRAME_acc_235_psp_sva;
  wire [5:0] FRAME_acc_236_psp_sva;
  wire [7:0] nl_FRAME_acc_236_psp_sva;
  wire [14:0] FRAME_acc_502_psp;
  wire [15:0] nl_FRAME_acc_502_psp;
  wire [15:0] FRAME_acc_362_sdt;
  wire [16:0] nl_FRAME_acc_362_sdt;
  wire [15:0] blue_x_sva;
  wire [16:0] nl_blue_x_sva;
  wire [14:0] FRAME_acc_486_psp;
  wire [15:0] nl_FRAME_acc_486_psp;
  wire [15:0] FRAME_acc_343_sdt;
  wire [16:0] nl_FRAME_acc_343_sdt;
  wire [15:0] green_x_sva;
  wire [16:0] nl_green_x_sva;
  wire [15:0] FRAME_acc_324_sdt;
  wire [16:0] nl_FRAME_acc_324_sdt;
  wire [14:0] FRAME_acc_psp;
  wire [15:0] nl_FRAME_acc_psp;
  wire [15:0] FRAME_acc_sdt;
  wire [17:0] nl_FRAME_acc_sdt;
  wire [10:0] FRAME_acc_79_psp_sva;
  wire [11:0] nl_FRAME_acc_79_psp_sva;
  wire [10:0] acc_18_psp_sva;
  wire [11:0] nl_acc_18_psp_sva;
  wire [10:0] FRAME_acc_47_psp_sva;
  wire [11:0] nl_FRAME_acc_47_psp_sva;
  wire [10:0] FRAME_acc_19_psp_sva;
  wire [11:0] nl_FRAME_acc_19_psp_sva;
  wire [10:0] acc_17_psp_sva;
  wire [11:0] nl_acc_17_psp_sva;
  wire [15:0] FRAME_acc_301_sdt;
  wire [17:0] nl_FRAME_acc_301_sdt;
  wire [12:0] FRAME_acc_440_sdt;
  wire [13:0] nl_FRAME_acc_440_sdt;
  wire [11:0] FRAME_acc_285_sdt;
  wire [12:0] nl_FRAME_acc_285_sdt;
  wire [11:0] FRAME_acc_445_sdt;
  wire [12:0] nl_FRAME_acc_445_sdt;
  wire [15:0] FRAME_acc_278_sdt;
  wire [17:0] nl_FRAME_acc_278_sdt;
  wire [12:0] FRAME_acc_420_sdt;
  wire [13:0] nl_FRAME_acc_420_sdt;
  wire [11:0] FRAME_acc_262_sdt;
  wire [12:0] nl_FRAME_acc_262_sdt;
  wire [11:0] FRAME_acc_425_sdt;
  wire [12:0] nl_FRAME_acc_425_sdt;
  wire [10:0] FRAME_acc_406_sdt;
  wire [11:0] nl_FRAME_acc_406_sdt;
  wire [14:0] FRAME_acc_251_sdt;
  wire [15:0] nl_FRAME_acc_251_sdt;
  wire [11:0] FRAME_acc_239_sdt;
  wire [12:0] nl_FRAME_acc_239_sdt;
  wire [11:0] FRAME_acc_393_sdt;
  wire [12:0] nl_FRAME_acc_393_sdt;
  wire [11:0] acc_19_sdt;
  wire [12:0] nl_acc_19_sdt;
  wire [14:0] acc_sdt;
  wire [15:0] nl_acc_sdt;
  wire [14:0] acc_25_sdt;
  wire [15:0] nl_acc_25_sdt;
  wire [14:0] acc_27_sdt;
  wire [15:0] nl_acc_27_sdt;
  wire [10:0] acc_79_sdt;
  wire [11:0] nl_acc_79_sdt;
  wire [14:0] acc_31_sdt;
  wire [15:0] nl_acc_31_sdt;
  wire [11:0] acc_88_cse;
  wire [12:0] nl_acc_88_cse;
  wire [11:0] acc_70_cse;
  wire [12:0] nl_acc_70_cse;
  wire [13:0] acc_99_itm;
  wire [15:0] nl_acc_99_itm;
  wire [13:0] acc_37_itm;
  wire [14:0] nl_acc_37_itm;
  wire [12:0] acc_89_itm;
  wire [13:0] nl_acc_89_itm;
  wire [15:0] FRAME_acc_355_itm;
  wire [16:0] nl_FRAME_acc_355_itm;
  wire [13:0] acc_41_itm;
  wire [14:0] nl_acc_41_itm;
  wire [12:0] acc_91_itm;
  wire [13:0] nl_acc_91_itm;
  wire [15:0] FRAME_acc_336_itm;
  wire [16:0] nl_FRAME_acc_336_itm;
  wire [13:0] acc_45_itm;
  wire [14:0] nl_acc_45_itm;
  wire [15:0] FRAME_acc_317_itm;
  wire [16:0] nl_FRAME_acc_317_itm;
  wire [11:0] FRAME_acc_305_itm;
  wire [12:0] nl_FRAME_acc_305_itm;
  wire [10:0] FRAME_acc_187_itm;
  wire [11:0] nl_FRAME_acc_187_itm;
  wire [13:0] FRAME_acc_309_itm;
  wire [14:0] nl_FRAME_acc_309_itm;
  wire [11:0] acc_105_cse;
  wire [12:0] nl_acc_105_cse;


  // Interconnect Declarations for Component Instantiations 
  assign nl_FRAME_acc_228_psp_sva = conv_s2u_15_17(red_sva_1[15:1]) + conv_s2u_16_17(red_sva_1);
  assign FRAME_acc_228_psp_sva = nl_FRAME_acc_228_psp_sva[16:0];
  assign nl_FRAME_acc_230_psp_sva = conv_s2u_5_6({(FRAME_acc_229_psp_sva[4]) , 3'b0
      , (~ (FRAME_acc_229_psp_sva[4]))}) + (conv_u2s_4_6(FRAME_acc_229_psp_sva[3:0])
      + conv_s2s_2_6(~ (FRAME_acc_229_psp_sva[6:5])));
  assign FRAME_acc_230_psp_sva = nl_FRAME_acc_230_psp_sva[5:0];
  assign nl_FRAME_acc_229_psp_sva = (7'b1000011 + conv_u2s_6_7(conv_u2u_5_6(~ (FRAME_acc_228_psp_sva[9:5]))
      + conv_u2u_5_6({(~ (FRAME_acc_228_psp_sva[14])) , 3'b111 , (~ (FRAME_acc_228_psp_sva[14]))})))
      + (conv_s2s_6_7(conv_u2s_4_6(FRAME_acc_228_psp_sva[13:10]) + conv_s2s_2_6(~
      (FRAME_acc_228_psp_sva[16:15]))) + conv_u2s_5_7(FRAME_acc_228_psp_sva[4:0]));
  assign FRAME_acc_229_psp_sva = nl_FRAME_acc_229_psp_sva[6:0];
  assign nl_FRAME_acc_231_psp_sva = conv_s2u_15_17(green_sva_1[15:1]) + conv_s2u_16_17(green_sva_1);
  assign FRAME_acc_231_psp_sva = nl_FRAME_acc_231_psp_sva[16:0];
  assign nl_FRAME_acc_232_psp_sva = (7'b1000011 + conv_u2s_6_7(conv_u2u_5_6(~ (FRAME_acc_231_psp_sva[9:5]))
      + conv_u2u_5_6({(~ (FRAME_acc_231_psp_sva[14])) , 3'b111 , (~ (FRAME_acc_231_psp_sva[14]))})))
      + (conv_s2s_6_7(conv_u2s_4_6(FRAME_acc_231_psp_sva[13:10]) + conv_s2s_2_6(~
      (FRAME_acc_231_psp_sva[16:15]))) + conv_u2s_5_7(FRAME_acc_231_psp_sva[4:0]));
  assign FRAME_acc_232_psp_sva = nl_FRAME_acc_232_psp_sva[6:0];
  assign nl_FRAME_acc_233_psp_sva = conv_s2u_5_6({(FRAME_acc_232_psp_sva[4]) , 3'b0
      , (~ (FRAME_acc_232_psp_sva[4]))}) + (conv_u2s_4_6(FRAME_acc_232_psp_sva[3:0])
      + conv_s2s_2_6(~ (FRAME_acc_232_psp_sva[6:5])));
  assign FRAME_acc_233_psp_sva = nl_FRAME_acc_233_psp_sva[5:0];
  assign nl_FRAME_acc_234_psp_sva = conv_s2u_15_17(blue_sva_1[15:1]) + conv_s2u_16_17(blue_sva_1);
  assign FRAME_acc_234_psp_sva = nl_FRAME_acc_234_psp_sva[16:0];
  assign nl_FRAME_acc_235_psp_sva = (7'b1000011 + conv_u2s_6_7(conv_u2u_5_6(~ (FRAME_acc_234_psp_sva[9:5]))
      + conv_u2u_5_6({(~ (FRAME_acc_234_psp_sva[14])) , 3'b111 , (~ (FRAME_acc_234_psp_sva[14]))})))
      + (conv_s2s_6_7(conv_u2s_4_6(FRAME_acc_234_psp_sva[13:10]) + conv_s2s_2_6(~
      (FRAME_acc_234_psp_sva[16:15]))) + conv_u2s_5_7(FRAME_acc_234_psp_sva[4:0]));
  assign FRAME_acc_235_psp_sva = nl_FRAME_acc_235_psp_sva[6:0];
  assign nl_FRAME_acc_236_psp_sva = conv_s2u_5_6({(FRAME_acc_235_psp_sva[4]) , 3'b0
      , (~ (FRAME_acc_235_psp_sva[4]))}) + (conv_u2s_4_6(FRAME_acc_235_psp_sva[3:0])
      + conv_s2s_2_6(~ (FRAME_acc_235_psp_sva[6:5])));
  assign FRAME_acc_236_psp_sva = nl_FRAME_acc_236_psp_sva[5:0];
  assign nl_FRAME_acc_502_psp = (FRAME_acc_362_sdt[15:1]) + (readslicef_16_15_1((({3'b111
      , (({1'b1 , (~ (reg_regs_regs_0_sva_cse[9:0]))}) + ({1'b1 , (~ (regs_regs_3_sva_1[9:0]))}))
      , 2'b1}) + ({(conv_s2u_11_13({1'b1 , (~ (regs_regs_2_sva_1[9:0]))}) + conv_u2u_12_13(acc_89_itm[12:1]))
      , (acc_89_itm[0]) , (acc_37_itm[1]) , 1'b1}))));
  assign FRAME_acc_502_psp = nl_FRAME_acc_502_psp[14:0];
  assign nl_acc_19_sdt = conv_s2s_11_12(FRAME_acc_79_psp_sva) + conv_u2s_11_12({(reg_regs_regs_0_sva_cse[149:140])
      , 1'b1});
  assign acc_19_sdt = nl_acc_19_sdt[11:0];
  assign nl_acc_70_cse = conv_u2u_11_12(FRAME_acc_187_itm) + conv_s2u_10_12(acc_19_sdt[11:2]);
  assign acc_70_cse = nl_acc_70_cse[11:0];
  assign nl_acc_sdt = conv_s2u_14_15({acc_70_cse , (acc_19_sdt[1:0])}) + conv_s2u_14_15(FRAME_acc_355_itm[15:2]);
  assign acc_sdt = nl_acc_sdt[14:0];
  assign nl_acc_105_cse = conv_s2u_11_12(({1'b1 , (~ (reg_regs_regs_0_sva_cse[59:50]))})
      + 11'b1) + conv_s2u_11_12(acc_18_psp_sva);
  assign acc_105_cse = nl_acc_105_cse[11:0];
  assign nl_FRAME_acc_362_sdt = ({(conv_s2u_13_14({acc_105_cse , 1'b1}) + (acc_sdt[14:1]))
      , (acc_sdt[0]) , (FRAME_acc_355_itm[1])}) + ({4'b1111 , (readslicef_13_12_1((({2'b11
      , (~ (vin_rsc_mgc_in_wire_d[9:0])) , 1'b1}) + ({1'b1 , (~ (vin_rsc_mgc_in_wire_d[39:30]))
      , 2'b1}))))});
  assign FRAME_acc_362_sdt = nl_FRAME_acc_362_sdt[15:0];
  assign nl_blue_x_sva = ({(({1'b1 , (({1'b1 , (({2'b11 , (~ (regs_regs_slc_regs_regs_4_11_itm[9:1]))})
      + ({1'b1 , (~ (regs_regs_3_sva_1[39:30]))}))}) + ({1'b1 , (({1'b1 , (~ (regs_regs_3_sva_1[99:90]))})
      + ({1'b1 , (~ regs_regs_slc_regs_regs_4_8_itm)}))})) , (~ (regs_regs_slc_regs_regs_4_11_itm[0]))})
      + (FRAME_acc_301_sdt[15:2])) , (FRAME_acc_301_sdt[1:0])}) + ({2'b11 , (({2'b11
      , (({2'b11 , (~ (regs_regs_slc_regs_regs_4_14_itm[9:1]))}) + ({1'b1 , (~ (regs_regs_3_sva_1[9:0]))}))})
      + ({1'b1 , (({2'b11 , (~ (regs_regs_3_sva_1[129:121]))}) + ({1'b1 , (~ regs_regs_slc_regs_regs_4_5_itm)}))
      , (~ (regs_regs_3_sva_1[120]))})) , (~ (regs_regs_slc_regs_regs_4_14_itm[0]))});
  assign blue_x_sva = nl_blue_x_sva[15:0];
  assign nl_FRAME_acc_486_psp = (FRAME_acc_343_sdt[15:1]) + (readslicef_16_15_1((({3'b111
      , (({1'b1 , (~ (reg_regs_regs_0_sva_cse[19:10]))}) + ({1'b1 , (~ (regs_regs_3_sva_1[19:10]))}))
      , 2'b1}) + ({(conv_s2u_11_13({1'b1 , (~ (regs_regs_2_sva_1[19:10]))}) + conv_u2u_12_13(acc_91_itm[12:1]))
      , (acc_91_itm[0]) , (acc_41_itm[1]) , 1'b1}))));
  assign FRAME_acc_486_psp = nl_FRAME_acc_486_psp[14:0];
  assign nl_acc_25_sdt = conv_s2u_14_15({acc_70_cse , (acc_19_sdt[1:0])}) + conv_s2u_14_15(FRAME_acc_336_itm[15:2]);
  assign acc_25_sdt = nl_acc_25_sdt[14:0];
  assign nl_FRAME_acc_343_sdt = ({(conv_s2u_13_14({acc_105_cse , 1'b1}) + (acc_25_sdt[14:1]))
      , (acc_25_sdt[0]) , (FRAME_acc_336_itm[1])}) + ({4'b1111 , (readslicef_13_12_1((({2'b11
      , (~ (vin_rsc_mgc_in_wire_d[19:10])) , 1'b1}) + ({1'b1 , (~ (vin_rsc_mgc_in_wire_d[49:40]))
      , 2'b1}))))});
  assign FRAME_acc_343_sdt = nl_FRAME_acc_343_sdt[15:0];
  assign nl_green_x_sva = ({(({1'b1 , (({1'b1 , (({2'b11 , (~ (regs_regs_slc_regs_regs_4_10_itm[9:1]))})
      + ({1'b1 , (~ (regs_regs_3_sva_1[49:40]))}))}) + ({1'b1 , (({1'b1 , (~ (regs_regs_3_sva_1[109:100]))})
      + ({1'b1 , (~ regs_regs_slc_regs_regs_4_7_itm)}))})) , (~ (regs_regs_slc_regs_regs_4_10_itm[0]))})
      + (FRAME_acc_278_sdt[15:2])) , (FRAME_acc_278_sdt[1:0])}) + ({2'b11 , (({2'b11
      , (({2'b11 , (~ (regs_regs_slc_regs_regs_4_13_itm[9:1]))}) + ({1'b1 , (~ (regs_regs_3_sva_1[19:10]))}))})
      + ({1'b1 , (({2'b11 , (~ (regs_regs_3_sva_1[139:131]))}) + ({1'b1 , (~ regs_regs_slc_regs_regs_4_4_itm)}))
      , (~ (regs_regs_3_sva_1[130]))})) , (~ (regs_regs_slc_regs_regs_4_13_itm[0]))});
  assign green_x_sva = nl_green_x_sva[15:0];
  assign nl_acc_27_sdt = (FRAME_acc_324_sdt[15:1]) + conv_s2u_14_15({2'b10 , (({1'b1
      , (~ (reg_regs_regs_0_sva_cse[29:20]))}) + ({1'b1 , (~ (regs_regs_3_sva_1[29:20]))}))
      , (readslicef_2_1_1((({(acc_45_itm[1]) , 1'b1}) + 2'b11)))});
  assign acc_27_sdt = nl_acc_27_sdt[14:0];
  assign nl_acc_99_itm = (conv_u2u_13_14(conv_u2u_12_13(acc_88_cse) + conv_u2u_12_13(acc_45_itm[13:2]))
      + conv_u2u_11_14({(~ (regs_regs_2_sva_1[29:20])) , 1'b1})) + (acc_27_sdt[14:1]);
  assign acc_99_itm = nl_acc_99_itm[13:0];
  assign nl_acc_79_sdt = conv_s2u_10_11(FRAME_acc_79_psp_sva[10:1]) + conv_u2u_10_11(reg_regs_regs_0_sva_cse[149:140]);
  assign acc_79_sdt = nl_acc_79_sdt[10:0];
  assign nl_acc_31_sdt = conv_s2u_14_15({(conv_u2u_11_12(FRAME_acc_187_itm) + conv_s2u_10_12(acc_79_sdt[10:1]))
      , (acc_79_sdt[0]) , (FRAME_acc_79_psp_sva[0])}) + conv_s2u_14_15(FRAME_acc_317_itm[15:2]);
  assign acc_31_sdt = nl_acc_31_sdt[14:0];
  assign nl_FRAME_acc_324_sdt = ({(conv_s2u_13_14({acc_105_cse , 1'b1}) + (acc_31_sdt[14:1]))
      , (acc_31_sdt[0]) , (FRAME_acc_317_itm[1])}) + ({4'b1111 , (readslicef_13_12_1((({2'b11
      , (~ (vin_rsc_mgc_in_wire_d[29:20])) , 1'b1}) + ({1'b1 , (~ (vin_rsc_mgc_in_wire_d[59:50]))
      , 2'b1}))))});
  assign FRAME_acc_324_sdt = nl_FRAME_acc_324_sdt[15:0];
  assign nl_FRAME_acc_psp = (FRAME_acc_sdt[15:1]) + ({2'b11 , (({2'b11 , (FRAME_acc_406_sdt[10:1])})
      + ({1'b1 , (({1'b1 , (~ regs_regs_slc_regs_regs_4_3_itm)}) + ({1'b1 , (~ regs_regs_slc_regs_regs_4_22_itm)}))}))
      , (FRAME_acc_406_sdt[0])});
  assign FRAME_acc_psp = nl_FRAME_acc_psp[14:0];
  assign nl_FRAME_acc_sdt = ({((conv_u2u_12_13(FRAME_acc_251_sdt[14:3]) + conv_u2u_11_13({(~
      (regs_regs_3_sva_1[89:80])) , 1'b1})) + ({2'b10 , (({1'b1 , (~ (regs_regs_3_sva_1[119:110]))})
      + ({1'b1 , (~ regs_regs_slc_regs_regs_4_6_itm)}))})) , (FRAME_acc_251_sdt[2:0])})
      + (({(conv_s2u_13_14({(conv_u2u_11_12(conv_u2u_10_11(reg_regs_regs_0_sva_cse[59:50])
      + conv_u2u_10_11(reg_regs_regs_0_sva_cse[119:110])) + conv_s2u_11_12(acc_18_psp_sva))
      , 1'b1}) + conv_s2u_13_14({(conv_u2u_10_12(reg_regs_regs_0_sva_cse[89:80])
      + conv_s2u_9_12(FRAME_acc_239_sdt[11:3])) , (FRAME_acc_239_sdt[2])})) , (FRAME_acc_239_sdt[1:0])})
      + ({6'b111111 , (~ regs_regs_slc_regs_regs_4_21_itm)}));
  assign FRAME_acc_sdt = nl_FRAME_acc_sdt[15:0];
  assign nl_acc_37_itm = conv_u2u_13_14({(regs_regs_3_sva_1[119:110]) , 1'b0 , (regs_regs_2_sva_1[140])
      , 1'b1}) + conv_u2u_12_14({(readslicef_12_11_1((conv_u2u_11_12({regs_regs_slc_regs_regs_4_22_itm
      , 1'b1}) + conv_u2u_11_12({(regs_regs_2_sva_1[9:0]) , 1'b1})))) , 1'b1});
  assign acc_37_itm = nl_acc_37_itm[13:0];
  assign nl_acc_88_cse = conv_u2u_11_12(conv_u2u_9_11(regs_regs_2_sva_1[149:141])
      + conv_u2u_10_11(regs_regs_2_sva_1[149:140])) + conv_u2u_11_12({(reg_regs_regs_0_sva_cse[119:110])
      , (regs_regs_2_sva_1[110])});
  assign acc_88_cse = nl_acc_88_cse[11:0];
  assign nl_acc_89_itm = conv_u2u_12_13(acc_88_cse) + conv_u2u_12_13(acc_37_itm[13:2]);
  assign acc_89_itm = nl_acc_89_itm[12:0];
  assign nl_FRAME_acc_79_psp_sva = ({1'b1 , (~ regs_regs_slc_regs_regs_4_3_itm)})
      + 11'b1;
  assign FRAME_acc_79_psp_sva = nl_FRAME_acc_79_psp_sva[10:0];
  assign nl_acc_18_psp_sva = ({1'b1 , (~ (regs_regs_3_sva_1[59:50]))}) + 11'b1;
  assign acc_18_psp_sva = nl_acc_18_psp_sva[10:0];
  assign nl_FRAME_acc_355_itm = conv_s2s_15_16({(readslicef_15_14_1((conv_u2s_14_15({(FRAME_acc_309_itm[13:1])
      , 1'b1}) + conv_s2s_14_15({(readslicef_13_12_1((conv_s2u_11_13({(FRAME_acc_47_psp_sva[10:1])
      , 1'b1}) + conv_u2u_11_13({(vin_rsc_mgc_in_wire_d[119:110]) , 1'b1})))) , (readslicef_2_1_1((({(FRAME_acc_47_psp_sva[0])
      , 1'b1}) + 2'b11))) , 1'b1})))) , 1'b1}) + ({(FRAME_acc_305_itm[11:1]) , (regs_regs_2_sva_1[51:50])
      , 3'b1});
  assign FRAME_acc_355_itm = nl_FRAME_acc_355_itm[15:0];
  assign nl_FRAME_acc_47_psp_sva = ({1'b1 , (~ regs_regs_slc_regs_regs_4_2_itm)})
      + 11'b1;
  assign FRAME_acc_47_psp_sva = nl_FRAME_acc_47_psp_sva[10:0];
  assign nl_acc_41_itm = conv_u2u_13_14({(regs_regs_3_sva_1[119:110]) , 1'b0 , (regs_regs_2_sva_1[140])
      , 1'b1}) + conv_u2u_12_14({(readslicef_12_11_1((conv_u2u_11_12({regs_regs_slc_regs_regs_4_22_itm
      , 1'b1}) + conv_u2u_11_12({(regs_regs_2_sva_1[19:10]) , 1'b1})))) , 1'b1});
  assign acc_41_itm = nl_acc_41_itm[13:0];
  assign nl_acc_91_itm = conv_u2u_12_13(acc_88_cse) + conv_u2u_12_13(acc_41_itm[13:2]);
  assign acc_91_itm = nl_acc_91_itm[12:0];
  assign nl_FRAME_acc_336_itm = conv_s2s_15_16({(readslicef_15_14_1((conv_u2s_14_15({(FRAME_acc_309_itm[13:1])
      , 1'b1}) + conv_s2s_14_15({(readslicef_13_12_1((conv_s2u_11_13({(FRAME_acc_19_psp_sva[10:1])
      , 1'b1}) + conv_u2u_11_13({(vin_rsc_mgc_in_wire_d[119:110]) , 1'b1})))) , (readslicef_2_1_1((({(FRAME_acc_19_psp_sva[0])
      , 1'b1}) + 2'b11))) , 1'b1})))) , 1'b1}) + ({(FRAME_acc_305_itm[11:1]) , (regs_regs_2_sva_1[51:50])
      , 3'b1});
  assign FRAME_acc_336_itm = nl_FRAME_acc_336_itm[15:0];
  assign nl_FRAME_acc_19_psp_sva = ({1'b1 , (~ regs_regs_slc_regs_regs_4_1_itm)})
      + 11'b1;
  assign FRAME_acc_19_psp_sva = nl_FRAME_acc_19_psp_sva[10:0];
  assign nl_acc_45_itm = conv_u2u_13_14({(regs_regs_3_sva_1[119:110]) , 1'b0 , (regs_regs_2_sva_1[140])
      , 1'b1}) + conv_u2u_12_14({(readslicef_12_11_1((conv_u2u_11_12({(vin_rsc_mgc_in_wire_d[119:110])
      , 1'b1}) + conv_u2u_11_12({regs_regs_slc_regs_regs_4_22_itm , 1'b1})))) , 1'b1});
  assign acc_45_itm = nl_acc_45_itm[13:0];
  assign nl_FRAME_acc_317_itm = conv_s2s_15_16({(readslicef_15_14_1((conv_u2s_14_15({(FRAME_acc_309_itm[13:1])
      , 1'b1}) + conv_s2s_14_15({(readslicef_13_12_1((conv_s2u_11_13({(acc_17_psp_sva[10:1])
      , 1'b1}) + conv_u2u_11_13({(regs_regs_2_sva_1[29:20]) , 1'b1})))) , (readslicef_2_1_1((({(acc_17_psp_sva[0])
      , 1'b1}) + 2'b11))) , 1'b1})))) , 1'b1}) + ({(FRAME_acc_305_itm[11:1]) , (regs_regs_2_sva_1[51:50])
      , 3'b1});
  assign FRAME_acc_317_itm = nl_FRAME_acc_317_itm[15:0];
  assign nl_acc_17_psp_sva = ({1'b1 , (~ regs_regs_slc_regs_regs_4_itm)}) + 11'b1;
  assign acc_17_psp_sva = nl_acc_17_psp_sva[10:0];
  assign nl_FRAME_acc_301_sdt = ({(conv_s2u_11_12({1'b1 , (~ (regs_regs_3_sva_1[69:60]))})
      + conv_u2u_11_12(FRAME_acc_440_sdt[12:2])) , (FRAME_acc_440_sdt[1:0]) , (vin_rsc_mgc_in_wire_d[121:120])})
      + (conv_s2s_15_16({(conv_u2u_10_12(reg_regs_regs_0_sva_cse[69:60]) + conv_s2u_9_12(FRAME_acc_285_sdt[11:3]))
      , (FRAME_acc_285_sdt[2:0])}) + conv_u2s_14_16({(conv_u2u_11_12(conv_u2u_10_11(vin_rsc_mgc_in_wire_d[39:30])
      + conv_u2u_10_11(reg_regs_regs_0_sva_cse[69:60])) + conv_u2u_11_12(FRAME_acc_445_sdt[11:1]))
      , (FRAME_acc_445_sdt[0]) , (vin_rsc_mgc_in_wire_d[0])}));
  assign FRAME_acc_301_sdt = nl_FRAME_acc_301_sdt[15:0];
  assign nl_FRAME_acc_440_sdt = conv_u2u_12_13(conv_u2u_11_12(conv_u2u_10_11(regs_regs_3_sva_1[69:60])
      + conv_u2u_10_11(vin_rsc_mgc_in_wire_d[69:60])) + conv_u2u_11_12(conv_u2u_10_11(vin_rsc_mgc_in_wire_d[99:90])
      + conv_u2u_9_11({(conv_u2u_6_7(vin_rsc_mgc_in_wire_d[129:124]) + 7'b11) , (vin_rsc_mgc_in_wire_d[123:122])})))
      + conv_u2u_12_13({(conv_u2u_10_11(reg_regs_regs_0_sva_cse[39:30]) + conv_u2u_10_11(reg_regs_regs_0_sva_cse[99:90]))
      , 1'b1});
  assign FRAME_acc_440_sdt = nl_FRAME_acc_440_sdt[12:0];
  assign nl_FRAME_acc_285_sdt = conv_s2s_11_12(FRAME_acc_47_psp_sva) + conv_u2s_11_12({(reg_regs_regs_0_sva_cse[9:0])
      , 1'b1});
  assign FRAME_acc_285_sdt = nl_FRAME_acc_285_sdt[11:0];
  assign nl_FRAME_acc_445_sdt = conv_u2u_11_12(conv_u2u_10_11(vin_rsc_mgc_in_wire_d[69:60])
      + conv_u2u_10_11(regs_regs_slc_regs_regs_4_8_itm)) + conv_u2u_11_12(conv_u2u_10_11(reg_regs_regs_0_sva_cse[129:120])
      + conv_u2u_9_11(vin_rsc_mgc_in_wire_d[9:1]));
  assign FRAME_acc_445_sdt = nl_FRAME_acc_445_sdt[11:0];
  assign nl_FRAME_acc_278_sdt = ({(conv_s2u_11_12({1'b1 , (~ (regs_regs_3_sva_1[79:70]))})
      + conv_u2u_11_12(FRAME_acc_420_sdt[12:2])) , (FRAME_acc_420_sdt[1:0]) , (vin_rsc_mgc_in_wire_d[131:130])})
      + (conv_s2s_15_16({(conv_u2u_10_12(reg_regs_regs_0_sva_cse[79:70]) + conv_s2u_9_12(FRAME_acc_262_sdt[11:3]))
      , (FRAME_acc_262_sdt[2:0])}) + conv_u2s_14_16({(conv_u2u_11_12(conv_u2u_10_11(vin_rsc_mgc_in_wire_d[49:40])
      + conv_u2u_10_11(reg_regs_regs_0_sva_cse[79:70])) + conv_u2u_11_12(FRAME_acc_425_sdt[11:1]))
      , (FRAME_acc_425_sdt[0]) , (vin_rsc_mgc_in_wire_d[10])}));
  assign FRAME_acc_278_sdt = nl_FRAME_acc_278_sdt[15:0];
  assign nl_FRAME_acc_420_sdt = conv_u2u_12_13(conv_u2u_11_12(conv_u2u_10_11(regs_regs_3_sva_1[79:70])
      + conv_u2u_10_11(vin_rsc_mgc_in_wire_d[79:70])) + conv_u2u_11_12(conv_u2u_10_11(vin_rsc_mgc_in_wire_d[109:100])
      + conv_u2u_9_11({(conv_u2u_6_7(vin_rsc_mgc_in_wire_d[139:134]) + 7'b11) , (vin_rsc_mgc_in_wire_d[133:132])})))
      + conv_u2u_12_13({(conv_u2u_10_11(reg_regs_regs_0_sva_cse[49:40]) + conv_u2u_10_11(reg_regs_regs_0_sva_cse[109:100]))
      , 1'b1});
  assign FRAME_acc_420_sdt = nl_FRAME_acc_420_sdt[12:0];
  assign nl_FRAME_acc_262_sdt = conv_s2s_11_12(FRAME_acc_19_psp_sva) + conv_u2s_11_12({(reg_regs_regs_0_sva_cse[19:10])
      , 1'b1});
  assign FRAME_acc_262_sdt = nl_FRAME_acc_262_sdt[11:0];
  assign nl_FRAME_acc_425_sdt = conv_u2u_11_12(conv_u2u_10_11(vin_rsc_mgc_in_wire_d[79:70])
      + conv_u2u_10_11(regs_regs_slc_regs_regs_4_7_itm)) + conv_u2u_11_12(conv_u2u_10_11(reg_regs_regs_0_sva_cse[139:130])
      + conv_u2u_9_11(vin_rsc_mgc_in_wire_d[19:11]));
  assign FRAME_acc_425_sdt = nl_FRAME_acc_425_sdt[11:0];
  assign nl_FRAME_acc_406_sdt = ({1'b1 , (~ (regs_regs_3_sva_1[29:20]))}) + ({1'b1
      , (~ (regs_regs_3_sva_1[149:140]))});
  assign FRAME_acc_406_sdt = nl_FRAME_acc_406_sdt[10:0];
  assign nl_FRAME_acc_251_sdt = conv_u2u_14_15({(conv_u2u_11_12(conv_u2u_10_11(vin_rsc_mgc_in_wire_d[59:50])
      + conv_u2u_10_11(reg_regs_regs_0_sva_cse[89:80])) + conv_u2u_11_12(FRAME_acc_393_sdt[11:1]))
      , (FRAME_acc_393_sdt[0]) , (vin_rsc_mgc_in_wire_d[20])}) + conv_u2u_14_15({(conv_u2u_11_12(conv_u2u_10_11(regs_regs_3_sva_1[89:80])
      + conv_u2u_10_11(vin_rsc_mgc_in_wire_d[89:80])) + conv_u2u_11_12(conv_u2u_10_11(vin_rsc_mgc_in_wire_d[119:110])
      + conv_u2u_9_11({(conv_u2u_5_6(vin_rsc_mgc_in_wire_d[149:145]) + 6'b1) , (vin_rsc_mgc_in_wire_d[144:142])})))
      , (vin_rsc_mgc_in_wire_d[141:140])});
  assign FRAME_acc_251_sdt = nl_FRAME_acc_251_sdt[14:0];
  assign nl_FRAME_acc_239_sdt = conv_s2s_11_12(acc_17_psp_sva) + conv_u2s_11_12({(reg_regs_regs_0_sva_cse[29:20])
      , 1'b1});
  assign FRAME_acc_239_sdt = nl_FRAME_acc_239_sdt[11:0];
  assign nl_FRAME_acc_393_sdt = conv_u2u_11_12(conv_u2u_10_11(vin_rsc_mgc_in_wire_d[89:80])
      + conv_u2u_10_11(regs_regs_slc_regs_regs_4_6_itm)) + conv_u2u_11_12(conv_u2u_10_11(reg_regs_regs_0_sva_cse[149:140])
      + conv_u2u_9_11(vin_rsc_mgc_in_wire_d[29:21]));
  assign FRAME_acc_393_sdt = nl_FRAME_acc_393_sdt[11:0];
  assign nl_FRAME_acc_305_itm = conv_u2s_9_12({(regs_regs_2_sva_1[59:52]) , 1'b1})
      + ({1'b1 , (~ (regs_regs_2_sva_1[59:50])) , 1'b1});
  assign FRAME_acc_305_itm = nl_FRAME_acc_305_itm[11:0];
  assign nl_FRAME_acc_187_itm = conv_u2u_9_11(regs_regs_2_sva_1[119:111]) + conv_u2u_10_11(regs_regs_2_sva_1[119:110]);
  assign FRAME_acc_187_itm = nl_FRAME_acc_187_itm[10:0];
  assign nl_FRAME_acc_309_itm = conv_u2u_13_14({(regs_regs_3_sva_1[149:140]) , 3'b1})
      + conv_u2u_12_14({(readslicef_12_11_1((conv_u2u_11_12({(vin_rsc_mgc_in_wire_d[149:140])
      , 1'b1}) + conv_u2u_11_12({regs_regs_slc_regs_regs_4_21_itm , 1'b1})))) , 1'b1});
  assign FRAME_acc_309_itm = nl_FRAME_acc_309_itm[13:0];
  always @(posedge clk or negedge arst_n) begin
    if ( ~ arst_n ) begin
      vout_rsc_mgc_out_stdreg_d <= 30'b0;
      red_sva_1 <= 16'b0;
      green_sva_1 <= 16'b0;
      blue_sva_1 <= 16'b0;
      main_stage_0_2 <= 1'b0;
      reg_regs_regs_0_sva_cse <= 150'b0;
      regs_regs_3_sva_1 <= 150'b0;
      regs_regs_2_sva_1 <= 150'b0;
      regs_regs_slc_regs_regs_4_22_itm <= 10'b0;
      regs_regs_slc_regs_regs_4_21_itm <= 10'b0;
      regs_regs_slc_regs_regs_4_3_itm <= 10'b0;
      regs_regs_slc_regs_regs_4_11_itm <= 10'b0;
      regs_regs_slc_regs_regs_4_8_itm <= 10'b0;
      regs_regs_slc_regs_regs_4_14_itm <= 10'b0;
      regs_regs_slc_regs_regs_4_5_itm <= 10'b0;
      regs_regs_slc_regs_regs_4_2_itm <= 10'b0;
      regs_regs_slc_regs_regs_4_10_itm <= 10'b0;
      regs_regs_slc_regs_regs_4_7_itm <= 10'b0;
      regs_regs_slc_regs_regs_4_13_itm <= 10'b0;
      regs_regs_slc_regs_regs_4_4_itm <= 10'b0;
      regs_regs_slc_regs_regs_4_1_itm <= 10'b0;
      regs_regs_slc_regs_regs_4_6_itm <= 10'b0;
      regs_regs_slc_regs_regs_4_itm <= 10'b0;
    end
    else begin
      if ( en ) begin
        vout_rsc_mgc_out_stdreg_d <= MUX_v_30_2_2({vout_rsc_mgc_out_stdreg_d , (({(({((readslicef_11_10_1((({conv_u2u_20_10(conv_s2s_2_10(FRAME_acc_228_psp_sva[16:15])
            * 10'b1111100001) , 1'b1}) + conv_u2u_10_11(signext_10_6({(FRAME_acc_228_psp_sva[14])
            , 3'b0 , (FRAME_acc_228_psp_sva[14]) , ((FRAME_acc_228_psp_sva[16]) &
            (~ (FRAME_acc_230_psp_sva[5])) & ((FRAME_acc_230_psp_sva[4]) | (FRAME_acc_230_psp_sva[3])
            | (FRAME_acc_230_psp_sva[2]) | (FRAME_acc_230_psp_sva[1]) | (FRAME_acc_230_psp_sva[0])
            | (red_sva_1[0])))}))))) + (readslicef_11_10_1((conv_u2s_10_11({(FRAME_acc_228_psp_sva[13:5])
            , 1'b1}) + conv_s2s_7_11({(readslicef_7_6_1((conv_s2s_6_7({1'b1 , (~
            (FRAME_acc_228_psp_sva[13:10])) , 1'b1}) + conv_s2s_3_7(FRAME_acc_229_psp_sva[6:4]))))
            , (~((FRAME_acc_230_psp_sva[5]) & (~ (FRAME_acc_228_psp_sva[16]))))})))))
            , 10'b0}) | (signext_20_12(conv_s2s_11_12(readslicef_12_11_1((({(readslicef_12_11_1((conv_u2s_10_12({(FRAME_acc_231_psp_sva[13:5])
            , 1'b1}) + conv_s2s_7_12({(readslicef_7_6_1((conv_s2s_6_7({1'b1 , (~
            (FRAME_acc_231_psp_sva[13:10])) , 1'b1}) + conv_s2s_3_7(FRAME_acc_232_psp_sva[6:4]))))
            , (~((FRAME_acc_233_psp_sva[5]) & (~ (FRAME_acc_231_psp_sva[16]))))}))))
            , 1'b1}) + conv_u2s_10_12(signext_10_6({(FRAME_acc_231_psp_sva[14]) ,
            3'b0 , (FRAME_acc_231_psp_sva[14]) , ((FRAME_acc_231_psp_sva[16]) & (~
            (FRAME_acc_233_psp_sva[5])) & ((FRAME_acc_233_psp_sva[4]) | (FRAME_acc_233_psp_sva[3])
            | (FRAME_acc_233_psp_sva[2]) | (FRAME_acc_233_psp_sva[1]) | (FRAME_acc_233_psp_sva[0])
            | (green_sva_1[0])))}))))) + conv_u2s_24_12(conv_s2s_2_12(FRAME_acc_231_psp_sva[16:15])
            * 12'b1111100001)))) , 10'b0}) | (signext_30_12(conv_s2s_11_12(readslicef_12_11_1((({(readslicef_12_11_1((conv_u2s_10_12({(FRAME_acc_234_psp_sva[13:5])
            , 1'b1}) + conv_s2s_7_12({(readslicef_7_6_1((conv_s2s_6_7({1'b1 , (~
            (FRAME_acc_234_psp_sva[13:10])) , 1'b1}) + conv_s2s_3_7(FRAME_acc_235_psp_sva[6:4]))))
            , (~((FRAME_acc_236_psp_sva[5]) & (~ (FRAME_acc_234_psp_sva[16]))))}))))
            , 1'b1}) + conv_u2s_10_12(signext_10_6({(FRAME_acc_234_psp_sva[14]) ,
            3'b0 , (FRAME_acc_234_psp_sva[14]) , ((FRAME_acc_234_psp_sva[16]) & (~
            (FRAME_acc_236_psp_sva[5])) & ((FRAME_acc_236_psp_sva[4]) | (FRAME_acc_236_psp_sva[3])
            | (FRAME_acc_236_psp_sva[2]) | (FRAME_acc_236_psp_sva[1]) | (FRAME_acc_236_psp_sva[0])
            | (blue_sva_1[0])))}))))) + conv_u2s_24_12(conv_s2s_2_12(FRAME_acc_234_psp_sva[16:15])
            * 12'b1111100001))))}, main_stage_0_2);
        red_sva_1 <= nl_red_sva_1[15:0];
        green_sva_1 <= nl_green_sva_1[15:0];
        blue_sva_1 <= nl_blue_sva_1[15:0];
        main_stage_0_2 <= 1'b1;
        reg_regs_regs_0_sva_cse <= vin_rsc_mgc_in_wire_d;
        regs_regs_3_sva_1 <= regs_regs_2_sva_1;
        regs_regs_2_sva_1 <= reg_regs_regs_0_sva_cse;
        regs_regs_slc_regs_regs_4_22_itm <= regs_regs_3_sva_1[119:110];
        regs_regs_slc_regs_regs_4_21_itm <= regs_regs_3_sva_1[149:140];
        regs_regs_slc_regs_regs_4_3_itm <= regs_regs_3_sva_1[59:50];
        regs_regs_slc_regs_regs_4_11_itm <= regs_regs_3_sva_1[99:90];
        regs_regs_slc_regs_regs_4_8_itm <= regs_regs_3_sva_1[69:60];
        regs_regs_slc_regs_regs_4_14_itm <= regs_regs_3_sva_1[129:120];
        regs_regs_slc_regs_regs_4_5_itm <= regs_regs_3_sva_1[39:30];
        regs_regs_slc_regs_regs_4_2_itm <= regs_regs_3_sva_1[9:0];
        regs_regs_slc_regs_regs_4_10_itm <= regs_regs_3_sva_1[109:100];
        regs_regs_slc_regs_regs_4_7_itm <= regs_regs_3_sva_1[79:70];
        regs_regs_slc_regs_regs_4_13_itm <= regs_regs_3_sva_1[139:130];
        regs_regs_slc_regs_regs_4_4_itm <= regs_regs_3_sva_1[49:40];
        regs_regs_slc_regs_regs_4_1_itm <= regs_regs_3_sva_1[19:10];
        regs_regs_slc_regs_regs_4_6_itm <= regs_regs_3_sva_1[89:80];
        regs_regs_slc_regs_regs_4_itm <= regs_regs_3_sva_1[29:20];
      end
    end
  end
  assign nl_red_sva_1  = (readslicef_17_16_1((conv_u2u_16_17({((acc_99_itm[12]) ^
      (acc_99_itm[13])) , ((acc_99_itm[11]) ^ (acc_99_itm[13])) , ((acc_99_itm[10])
      ^ (acc_99_itm[13])) , ((acc_99_itm[9]) ^ (acc_99_itm[13])) , ((acc_99_itm[8])
      ^ (acc_99_itm[13])) , ((acc_99_itm[7]) ^ (acc_99_itm[13])) , ((acc_99_itm[6])
      ^ (acc_99_itm[13])) , ((acc_99_itm[5]) ^ (acc_99_itm[13])) , ((acc_99_itm[4])
      ^ (acc_99_itm[13])) , ((acc_99_itm[3]) ^ (acc_99_itm[13])) , ((acc_99_itm[2])
      ^ (acc_99_itm[13])) , ((acc_99_itm[1]) ^ (acc_99_itm[13])) , ((acc_99_itm[0])
      ^ (acc_99_itm[13])) , ((acc_27_sdt[0]) ^ (acc_99_itm[13])) , ((FRAME_acc_324_sdt[0])
      ^ (acc_99_itm[13])) , 1'b1}) + conv_u2u_2_17({(FRAME_acc_psp[14]) , (acc_99_itm[13])}))))
      + conv_u2s_15_16({((FRAME_acc_psp[13]) ^ (FRAME_acc_psp[14])) , ((FRAME_acc_psp[12])
      ^ (FRAME_acc_psp[14])) , ((FRAME_acc_psp[11]) ^ (FRAME_acc_psp[14])) , ((FRAME_acc_psp[10])
      ^ (FRAME_acc_psp[14])) , ((FRAME_acc_psp[9]) ^ (FRAME_acc_psp[14])) , ((FRAME_acc_psp[8])
      ^ (FRAME_acc_psp[14])) , ((FRAME_acc_psp[7]) ^ (FRAME_acc_psp[14])) , ((FRAME_acc_psp[6])
      ^ (FRAME_acc_psp[14])) , ((FRAME_acc_psp[5]) ^ (FRAME_acc_psp[14])) , ((FRAME_acc_psp[4])
      ^ (FRAME_acc_psp[14])) , ((FRAME_acc_psp[3]) ^ (FRAME_acc_psp[14])) , ((FRAME_acc_psp[2])
      ^ (FRAME_acc_psp[14])) , ((FRAME_acc_psp[1]) ^ (FRAME_acc_psp[14])) , ((FRAME_acc_psp[0])
      ^ (FRAME_acc_psp[14])) , ((FRAME_acc_sdt[0]) ^ (FRAME_acc_psp[14]))});
  assign nl_green_sva_1  = (readslicef_17_16_1((conv_u2u_16_17({((FRAME_acc_486_psp[13])
      ^ (FRAME_acc_486_psp[14])) , ((FRAME_acc_486_psp[12]) ^ (FRAME_acc_486_psp[14]))
      , ((FRAME_acc_486_psp[11]) ^ (FRAME_acc_486_psp[14])) , ((FRAME_acc_486_psp[10])
      ^ (FRAME_acc_486_psp[14])) , ((FRAME_acc_486_psp[9]) ^ (FRAME_acc_486_psp[14]))
      , ((FRAME_acc_486_psp[8]) ^ (FRAME_acc_486_psp[14])) , ((FRAME_acc_486_psp[7])
      ^ (FRAME_acc_486_psp[14])) , ((FRAME_acc_486_psp[6]) ^ (FRAME_acc_486_psp[14]))
      , ((FRAME_acc_486_psp[5]) ^ (FRAME_acc_486_psp[14])) , ((FRAME_acc_486_psp[4])
      ^ (FRAME_acc_486_psp[14])) , ((FRAME_acc_486_psp[3]) ^ (FRAME_acc_486_psp[14]))
      , ((FRAME_acc_486_psp[2]) ^ (FRAME_acc_486_psp[14])) , ((FRAME_acc_486_psp[1])
      ^ (FRAME_acc_486_psp[14])) , ((FRAME_acc_486_psp[0]) ^ (FRAME_acc_486_psp[14]))
      , ((FRAME_acc_343_sdt[0]) ^ (FRAME_acc_486_psp[14])) , 1'b1}) + conv_u2u_2_17({(green_x_sva[15])
      , (FRAME_acc_486_psp[14])})))) + conv_u2s_15_16({((green_x_sva[14]) ^ (green_x_sva[15]))
      , ((green_x_sva[13]) ^ (green_x_sva[15])) , ((green_x_sva[12]) ^ (green_x_sva[15]))
      , ((green_x_sva[11]) ^ (green_x_sva[15])) , ((green_x_sva[10]) ^ (green_x_sva[15]))
      , ((green_x_sva[9]) ^ (green_x_sva[15])) , ((green_x_sva[8]) ^ (green_x_sva[15]))
      , ((green_x_sva[7]) ^ (green_x_sva[15])) , ((green_x_sva[6]) ^ (green_x_sva[15]))
      , ((green_x_sva[5]) ^ (green_x_sva[15])) , ((green_x_sva[4]) ^ (green_x_sva[15]))
      , ((green_x_sva[3]) ^ (green_x_sva[15])) , ((green_x_sva[2]) ^ (green_x_sva[15]))
      , ((green_x_sva[1]) ^ (green_x_sva[15])) , ((green_x_sva[0]) ^ (green_x_sva[15]))});
  assign nl_blue_sva_1  = (readslicef_17_16_1((conv_u2u_16_17({((FRAME_acc_502_psp[13])
      ^ (FRAME_acc_502_psp[14])) , ((FRAME_acc_502_psp[12]) ^ (FRAME_acc_502_psp[14]))
      , ((FRAME_acc_502_psp[11]) ^ (FRAME_acc_502_psp[14])) , ((FRAME_acc_502_psp[10])
      ^ (FRAME_acc_502_psp[14])) , ((FRAME_acc_502_psp[9]) ^ (FRAME_acc_502_psp[14]))
      , ((FRAME_acc_502_psp[8]) ^ (FRAME_acc_502_psp[14])) , ((FRAME_acc_502_psp[7])
      ^ (FRAME_acc_502_psp[14])) , ((FRAME_acc_502_psp[6]) ^ (FRAME_acc_502_psp[14]))
      , ((FRAME_acc_502_psp[5]) ^ (FRAME_acc_502_psp[14])) , ((FRAME_acc_502_psp[4])
      ^ (FRAME_acc_502_psp[14])) , ((FRAME_acc_502_psp[3]) ^ (FRAME_acc_502_psp[14]))
      , ((FRAME_acc_502_psp[2]) ^ (FRAME_acc_502_psp[14])) , ((FRAME_acc_502_psp[1])
      ^ (FRAME_acc_502_psp[14])) , ((FRAME_acc_502_psp[0]) ^ (FRAME_acc_502_psp[14]))
      , ((FRAME_acc_362_sdt[0]) ^ (FRAME_acc_502_psp[14])) , 1'b1}) + conv_u2u_2_17({(blue_x_sva[15])
      , (FRAME_acc_502_psp[14])})))) + conv_u2s_15_16({((blue_x_sva[14]) ^ (blue_x_sva[15]))
      , ((blue_x_sva[13]) ^ (blue_x_sva[15])) , ((blue_x_sva[12]) ^ (blue_x_sva[15]))
      , ((blue_x_sva[11]) ^ (blue_x_sva[15])) , ((blue_x_sva[10]) ^ (blue_x_sva[15]))
      , ((blue_x_sva[9]) ^ (blue_x_sva[15])) , ((blue_x_sva[8]) ^ (blue_x_sva[15]))
      , ((blue_x_sva[7]) ^ (blue_x_sva[15])) , ((blue_x_sva[6]) ^ (blue_x_sva[15]))
      , ((blue_x_sva[5]) ^ (blue_x_sva[15])) , ((blue_x_sva[4]) ^ (blue_x_sva[15]))
      , ((blue_x_sva[3]) ^ (blue_x_sva[15])) , ((blue_x_sva[2]) ^ (blue_x_sva[15]))
      , ((blue_x_sva[1]) ^ (blue_x_sva[15])) , ((blue_x_sva[0]) ^ (blue_x_sva[15]))});

  function [14:0] readslicef_16_15_1;
    input [15:0] vector;
    reg [15:0] tmp;
  begin
    tmp = vector >> 1;
    readslicef_16_15_1 = tmp[14:0];
  end
  endfunction


  function [11:0] readslicef_13_12_1;
    input [12:0] vector;
    reg [12:0] tmp;
  begin
    tmp = vector >> 1;
    readslicef_13_12_1 = tmp[11:0];
  end
  endfunction


  function [0:0] readslicef_2_1_1;
    input [1:0] vector;
    reg [1:0] tmp;
  begin
    tmp = vector >> 1;
    readslicef_2_1_1 = tmp[0:0];
  end
  endfunction


  function [10:0] readslicef_12_11_1;
    input [11:0] vector;
    reg [11:0] tmp;
  begin
    tmp = vector >> 1;
    readslicef_12_11_1 = tmp[10:0];
  end
  endfunction


  function [13:0] readslicef_15_14_1;
    input [14:0] vector;
    reg [14:0] tmp;
  begin
    tmp = vector >> 1;
    readslicef_15_14_1 = tmp[13:0];
  end
  endfunction


  function [29:0] MUX_v_30_2_2;
    input [59:0] inputs;
    input [0:0] sel;
    reg [29:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = inputs[59:30];
      end
      1'b1 : begin
        result = inputs[29:0];
      end
      default : begin
        result = inputs[59:30];
      end
    endcase
    MUX_v_30_2_2 = result;
  end
  endfunction


  function [9:0] readslicef_11_10_1;
    input [10:0] vector;
    reg [10:0] tmp;
  begin
    tmp = vector >> 1;
    readslicef_11_10_1 = tmp[9:0];
  end
  endfunction


  function [9:0] signext_10_6;
    input [5:0] vector;
  begin
    signext_10_6= {{4{vector[5]}}, vector};
  end
  endfunction


  function [5:0] readslicef_7_6_1;
    input [6:0] vector;
    reg [6:0] tmp;
  begin
    tmp = vector >> 1;
    readslicef_7_6_1 = tmp[5:0];
  end
  endfunction


  function [19:0] signext_20_12;
    input [11:0] vector;
  begin
    signext_20_12= {{8{vector[11]}}, vector};
  end
  endfunction


  function [29:0] signext_30_12;
    input [11:0] vector;
  begin
    signext_30_12= {{18{vector[11]}}, vector};
  end
  endfunction


  function [15:0] readslicef_17_16_1;
    input [16:0] vector;
    reg [16:0] tmp;
  begin
    tmp = vector >> 1;
    readslicef_17_16_1 = tmp[15:0];
  end
  endfunction


  function  [16:0] conv_s2u_15_17 ;
    input signed [14:0]  vector ;
  begin
    conv_s2u_15_17 = {{2{vector[14]}}, vector};
  end
  endfunction


  function  [16:0] conv_s2u_16_17 ;
    input signed [15:0]  vector ;
  begin
    conv_s2u_16_17 = {vector[15], vector};
  end
  endfunction


  function  [5:0] conv_s2u_5_6 ;
    input signed [4:0]  vector ;
  begin
    conv_s2u_5_6 = {vector[4], vector};
  end
  endfunction


  function signed [5:0] conv_u2s_4_6 ;
    input [3:0]  vector ;
  begin
    conv_u2s_4_6 = {{2{1'b0}}, vector};
  end
  endfunction


  function signed [5:0] conv_s2s_2_6 ;
    input signed [1:0]  vector ;
  begin
    conv_s2s_2_6 = {{4{vector[1]}}, vector};
  end
  endfunction


  function signed [6:0] conv_u2s_6_7 ;
    input [5:0]  vector ;
  begin
    conv_u2s_6_7 = {1'b0, vector};
  end
  endfunction


  function  [5:0] conv_u2u_5_6 ;
    input [4:0]  vector ;
  begin
    conv_u2u_5_6 = {1'b0, vector};
  end
  endfunction


  function signed [6:0] conv_s2s_6_7 ;
    input signed [5:0]  vector ;
  begin
    conv_s2s_6_7 = {vector[5], vector};
  end
  endfunction


  function signed [6:0] conv_u2s_5_7 ;
    input [4:0]  vector ;
  begin
    conv_u2s_5_7 = {{2{1'b0}}, vector};
  end
  endfunction


  function  [12:0] conv_s2u_11_13 ;
    input signed [10:0]  vector ;
  begin
    conv_s2u_11_13 = {{2{vector[10]}}, vector};
  end
  endfunction


  function  [12:0] conv_u2u_12_13 ;
    input [11:0]  vector ;
  begin
    conv_u2u_12_13 = {1'b0, vector};
  end
  endfunction


  function signed [11:0] conv_s2s_11_12 ;
    input signed [10:0]  vector ;
  begin
    conv_s2s_11_12 = {vector[10], vector};
  end
  endfunction


  function signed [11:0] conv_u2s_11_12 ;
    input [10:0]  vector ;
  begin
    conv_u2s_11_12 = {1'b0, vector};
  end
  endfunction


  function  [11:0] conv_u2u_11_12 ;
    input [10:0]  vector ;
  begin
    conv_u2u_11_12 = {1'b0, vector};
  end
  endfunction


  function  [11:0] conv_s2u_10_12 ;
    input signed [9:0]  vector ;
  begin
    conv_s2u_10_12 = {{2{vector[9]}}, vector};
  end
  endfunction


  function  [14:0] conv_s2u_14_15 ;
    input signed [13:0]  vector ;
  begin
    conv_s2u_14_15 = {vector[13], vector};
  end
  endfunction


  function  [11:0] conv_s2u_11_12 ;
    input signed [10:0]  vector ;
  begin
    conv_s2u_11_12 = {vector[10], vector};
  end
  endfunction


  function  [13:0] conv_s2u_13_14 ;
    input signed [12:0]  vector ;
  begin
    conv_s2u_13_14 = {vector[12], vector};
  end
  endfunction


  function  [13:0] conv_u2u_13_14 ;
    input [12:0]  vector ;
  begin
    conv_u2u_13_14 = {1'b0, vector};
  end
  endfunction


  function  [13:0] conv_u2u_11_14 ;
    input [10:0]  vector ;
  begin
    conv_u2u_11_14 = {{3{1'b0}}, vector};
  end
  endfunction


  function  [10:0] conv_s2u_10_11 ;
    input signed [9:0]  vector ;
  begin
    conv_s2u_10_11 = {vector[9], vector};
  end
  endfunction


  function  [10:0] conv_u2u_10_11 ;
    input [9:0]  vector ;
  begin
    conv_u2u_10_11 = {1'b0, vector};
  end
  endfunction


  function  [12:0] conv_u2u_11_13 ;
    input [10:0]  vector ;
  begin
    conv_u2u_11_13 = {{2{1'b0}}, vector};
  end
  endfunction


  function  [11:0] conv_u2u_10_12 ;
    input [9:0]  vector ;
  begin
    conv_u2u_10_12 = {{2{1'b0}}, vector};
  end
  endfunction


  function  [11:0] conv_s2u_9_12 ;
    input signed [8:0]  vector ;
  begin
    conv_s2u_9_12 = {{3{vector[8]}}, vector};
  end
  endfunction


  function  [13:0] conv_u2u_12_14 ;
    input [11:0]  vector ;
  begin
    conv_u2u_12_14 = {{2{1'b0}}, vector};
  end
  endfunction


  function  [10:0] conv_u2u_9_11 ;
    input [8:0]  vector ;
  begin
    conv_u2u_9_11 = {{2{1'b0}}, vector};
  end
  endfunction


  function signed [15:0] conv_s2s_15_16 ;
    input signed [14:0]  vector ;
  begin
    conv_s2s_15_16 = {vector[14], vector};
  end
  endfunction


  function signed [14:0] conv_u2s_14_15 ;
    input [13:0]  vector ;
  begin
    conv_u2s_14_15 = {1'b0, vector};
  end
  endfunction


  function signed [14:0] conv_s2s_14_15 ;
    input signed [13:0]  vector ;
  begin
    conv_s2s_14_15 = {vector[13], vector};
  end
  endfunction


  function signed [15:0] conv_u2s_14_16 ;
    input [13:0]  vector ;
  begin
    conv_u2s_14_16 = {{2{1'b0}}, vector};
  end
  endfunction


  function  [6:0] conv_u2u_6_7 ;
    input [5:0]  vector ;
  begin
    conv_u2u_6_7 = {1'b0, vector};
  end
  endfunction


  function  [14:0] conv_u2u_14_15 ;
    input [13:0]  vector ;
  begin
    conv_u2u_14_15 = {1'b0, vector};
  end
  endfunction


  function signed [11:0] conv_u2s_9_12 ;
    input [8:0]  vector ;
  begin
    conv_u2s_9_12 = {{3{1'b0}}, vector};
  end
  endfunction


  function  [9:0] conv_u2u_20_10 ;
    input [19:0]  vector ;
  begin
    conv_u2u_20_10 = vector[9:0];
  end
  endfunction


  function signed [9:0] conv_s2s_2_10 ;
    input signed [1:0]  vector ;
  begin
    conv_s2s_2_10 = {{8{vector[1]}}, vector};
  end
  endfunction


  function signed [10:0] conv_u2s_10_11 ;
    input [9:0]  vector ;
  begin
    conv_u2s_10_11 = {1'b0, vector};
  end
  endfunction


  function signed [10:0] conv_s2s_7_11 ;
    input signed [6:0]  vector ;
  begin
    conv_s2s_7_11 = {{4{vector[6]}}, vector};
  end
  endfunction


  function signed [6:0] conv_s2s_3_7 ;
    input signed [2:0]  vector ;
  begin
    conv_s2s_3_7 = {{4{vector[2]}}, vector};
  end
  endfunction


  function signed [11:0] conv_u2s_10_12 ;
    input [9:0]  vector ;
  begin
    conv_u2s_10_12 = {{2{1'b0}}, vector};
  end
  endfunction


  function signed [11:0] conv_s2s_7_12 ;
    input signed [6:0]  vector ;
  begin
    conv_s2s_7_12 = {{5{vector[6]}}, vector};
  end
  endfunction


  function signed [11:0] conv_u2s_24_12 ;
    input [23:0]  vector ;
  begin
    conv_u2s_24_12 = vector[11:0];
  end
  endfunction


  function signed [11:0] conv_s2s_2_12 ;
    input signed [1:0]  vector ;
  begin
    conv_s2s_2_12 = {{10{vector[1]}}, vector};
  end
  endfunction


  function  [16:0] conv_u2u_16_17 ;
    input [15:0]  vector ;
  begin
    conv_u2u_16_17 = {1'b0, vector};
  end
  endfunction


  function  [16:0] conv_u2u_2_17 ;
    input [1:0]  vector ;
  begin
    conv_u2u_2_17 = {{15{1'b0}}, vector};
  end
  endfunction


  function signed [15:0] conv_u2s_15_16 ;
    input [14:0]  vector ;
  begin
    conv_u2s_15_16 = {1'b0, vector};
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    mean_vga
//  Generated from file(s):
//   10) $PROJECT_HOME/../5x5 sobel color/blur.c
// ------------------------------------------------------------------


module mean_vga (
  vin_rsc_z, vout_rsc_z, clk, en, arst_n
);
  input [149:0] vin_rsc_z;
  output [29:0] vout_rsc_z;
  input clk;
  input en;
  input arst_n;


  // Interconnect Declarations
  wire [149:0] vin_rsc_mgc_in_wire_d;
  wire [29:0] vout_rsc_mgc_out_stdreg_d;


  // Interconnect Declarations for Component Instantiations 
  mgc_in_wire #(.rscid(1),
  .width(150)) vin_rsc_mgc_in_wire (
      .d(vin_rsc_mgc_in_wire_d),
      .z(vin_rsc_z)
    );
  mgc_out_stdreg #(.rscid(2),
  .width(30)) vout_rsc_mgc_out_stdreg (
      .d(vout_rsc_mgc_out_stdreg_d),
      .z(vout_rsc_z)
    );
  mean_vga_core mean_vga_core_inst (
      .clk(clk),
      .en(en),
      .arst_n(arst_n),
      .vin_rsc_mgc_in_wire_d(vin_rsc_mgc_in_wire_d),
      .vout_rsc_mgc_out_stdreg_d(vout_rsc_mgc_out_stdreg_d)
    );
endmodule



